### ISSUE TITLE
No Project Description 

### ISSUE THREAD

**Issue by eastman81** [danielryne/fireboard#10]
I tried added one and it wouldn't let me, I think Daniel has to do this because he created the Repo.

https://github.com/danielryne/fireboard/community

**Comment by danielryne** [comment]
Oh that's weird. I'm happy to do it if you want to send me whatever you
want to post.


LinkedIn <https://www.linkedin.com/in/danielrynelucio> | Twitter
<https://twitter.com/danielrynelucio> | Facebook
<https://www.facebook.com/danielrynelucio>
(pronouns: he/him)
